name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  make:
    strategy:
      matrix:
        target: [GZIP, NCOM, BC, YPSV, POLY]
        compiler: [gcc-12, clang-17]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install GCC
        if: matrix.compiler == 'gcc-12'
        run: sudo apt install -y gcc-12 gcc-12-multilib

      - name: Install Clang
        if: matrix.compiler == 'clang-17'
        run: |
          sudo apt install -y lsb-release wget software-properties-common gnupg
          curl -sSf https://apt.llvm.org/llvm.sh | sudo bash -s -- 17 all

      - name: Install dependencies
        run: sudo apt install -y bison libgdbm-dev

      - name: Make
        run: make CC=${{matrix.compiler}} ${{matrix.target}}
