name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  make:
    strategy:
      matrix:
        target: [GZIP, NCOM, BC, YPSV, CVS]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: sudo apt install -y bison gcc-multilib

      - name: Make
        run: make ${{matrix.target}}
